# Generated by Django 4.2.7 on 2024-03-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=32, verbose_name='Username')),
                ('Password', models.CharField(max_length=32, verbose_name='Password')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'users',
                'verbose_name_plural': 'user',
            },
        ),
    ]
