# Generated by Django 4.2.7 on 2024-03-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=32, verbose_name='Username')),
                ('Password', models.CharField(max_length=32, verbose_name='Password')),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='UserName',
            field=models.CharField(max_length=32, verbose_name='Username'),
        ),
    ]
